version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: aiboards-postgres
    environment:
      POSTGRES_USER: aiboards
      POSTGRES_PASSWORD: aiboards
      POSTGRES_DB: aiboards
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
